### ISSUE TITLE
Ubuntu 22.04 - Dependencies installed, but application won't start.  "/usr/bin/python: bad interpreter: No such file or directory"

### ISSUE THREAD

**Issue by mendhak** [fosspost/fp-collapse-monitor#1]
### Issue 

On Ubuntu 22.04, I have  installed the dependencies

    sudo apt install python3 python3-gi gir1.2-webkit2-4.0

And then installed the `.deb` file.  

    sudo apt install ./fp-collapse-monitor_1.0_all.deb

But when trying to run the application the application, it errors out

> $ fp-collapse-monitor 
bash: /usr/bin/fp-collapse-monitor: /usr/bin/python: bad interpreter: No such file or directory

### Workaround

The cause it seems, there's nothing providing `/usr/bin/python` on Ubuntu 22.04.  We can either symlink it or just install : 

    sudo apt install python-is-python3

**Comment by mhsabbagh** [comment]
Thanks for your report. Indeed `python3` has be specified for Ubuntu 22.04 LTS instead of python.

I'll fix this by changing the default Python path to `#!/usr/bin/env python3`, because this works on both 20.04 and 22.04 (And all distributions based on them), so it should be the best option.
